mshr-h/vscode-verilog-hdl-support

package.json
src/extension.ts
src/linter/BaseLinter.ts
src/linter/IcarusLinter.ts
src/linter/XvlogLinter.ts

I added support for xvlog which is distributed along with Xilinx's Vivado tool.
Also restructured the extension for easier addition of linters.

Added support for linting with Vivado Simulator's xvlog.

---

CHANGELOG.md
README.md
package.json
src/extension.ts
src/linter/ModelsimLinter.ts

Added support for linting using Modelsim

Modelsim linter support

---

CHANGELOG.md
package.json

Fixed dependencies in package.json
Added entry in Changelog for 0.3.4
Referring to #32

Minor fixes to package.json and Changelog

---

CONTRIBUTING.md
README.md

Referring #25 
* Reorganized Readme
- Clear list of Configuration settings
- A table of compatibility
- Thanks to contributors and prior work
* Added Contribution Guidelines "CONTRIBUTING.md"
- Pointed people willing to contribute to #25 
- Mentioned to update Changelog and Readme
These Contribution Guidelines are just a draft. Feedback is welcome.
@HansLehnert , @terriblefire 
Can you please check if the documentation regarding the features you added are proper in the Readme?
If you can mention the resources you used, I can add that with this PR.

Reorganizing Readme

---

src/ctags.ts
src/extension.ts
src/providers/CompletionItemProvider.ts

basic completion item provider with ctags
referring #25

basic completion item provider

---

src/extension.ts
src/linter/BaseLinter.ts
src/linter/IcarusLinter.ts
src/linter/LintManager.ts
src/linter/ModelsimLinter.ts
src/linter/VerilatorLinter.ts
src/linter/XvlogLinter.ts

Updated the code to support sv in linters
Fixing #42 
Referring #25

Adding support for SystemVerilog linting

---

.github/ISSUE_TEMPLATE/bug_report.md
CHANGELOG.md
README.md
package.json
src/Logger.ts
src/commands/ModuleInstantiation.ts
src/ctags.ts
src/extension.ts
src/linter/BaseLinter.ts
src/linter/IcarusLinter.ts
src/linter/LintManager.ts
src/linter/ModelsimLinter.ts
src/linter/VerilatorLinter.ts
src/linter/XvlogLinter.ts
src/providers/CompletionItemProvider.ts
src/providers/DefinitionProvider.ts
src/providers/DocumentSymbolProvider.ts
src/providers/HoverProvider.ts

Added logging to Output panel in VS Code. This should help make debugging issues easy.
Enable logging by setting `verilog.logging.enabled` to `true`.

Added basic logging

---

systemverilog.configuration.json
verilog.configuration.json

I've updated language configuration for better bracket-matching and auto-closing.
* Add block keywords to brackets
* Add double quote to autoClosingPairs
* Enable autoclosing in string and comment

Update language configuration

---

README.md

Just tried it and it works very  well
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mshr-h/vscode-verilog-hdl-support/108)

OSX + iverilog linter compatibility update

---

CHANGELOG.md
src/linter/VerilatorLinter.ts

Fix linter parsing issues due to recent changes in Verilator report formatting.

Verilator linter compatibility fix

---

.github/workflows/ci.yml

Use actions/setup-node@v2

---

package.json
src/linter/IcarusLinter.ts
src/linter/ModelsimLinter.ts
src/linter/VerilatorLinter.ts
src/linter/XvlogLinter.ts

Added the opportunity to indicate the path to `linter`.
This question is raised in many `Issues', users have such a need.
In order not to produce the number of parameters, it was decided to make one Path field in which the set Linter will already be searched.

Added the ability to specify PATH for linter

---

package.json

activate extension when supported file opened

---

systemverilog.configuration.json
verilog.configuration.json

issue：https://github.com/mshr-h/vscode-verilog-hdl-support/issues/328

Add verilog/systemverilog language folding marker

---

README.md
package.json
src/extension.ts
syntaxes/vhdl.tmLanguage
vhdl.configuration.json

Add VHDL support

---

CHANGELOG.md
README.md
configs/verilog-filelist.configuration.json
package.json
syntaxes/verilog-filelist.tmLanguage.json

Adds basic syntax highlighting for Verilog Filelists (dot-F files)

Syntax highlighting for Filelists

---

CHANGELOG.md
README.md
package.json
src/BsvProvider.ts
src/extension.ts
src/linter/VerilatorLinter.ts
src/logger.ts
src/providers/FormatPrivider.ts

Add Verilog-HDL formatting with verilog-format

---

src/providers/FormatPrivider.ts

Refactor formatting

---

src/commands/ModuleInstantiation.ts
src/extension.ts

Fix Instantiate Module

---

src/BsvProvider.ts
src/bsvLanguageServer/bsvLanguage.ts
src/commands/ModuleInstantiation.ts
src/ctags.ts
src/extension.ts
src/extensionManager.ts
src/hover.ts
src/linter/BaseLinter.ts
src/linter/IcarusLinter.ts
src/linter/LintManager.ts
src/linter/ModelsimLinter.ts
src/linter/SlangLinter.ts
src/linter/VerilatorLinter.ts
src/linter/XvlogLinter.ts
src/providers/CompletionItemProvider.ts
src/providers/DefinitionProvider.ts
src/providers/DocumentSymbolProvider.ts
src/providers/FormatPrivider.ts
src/providers/HoverProvider.ts
src/test/bsv.ts
src/test/runTest.ts
src/test/suite/bsv.test.ts
src/test/suite/extension.test.ts
src/test/suite/index.ts

Add SPDX-License-Identifier

---

src/linter/IcarusLinter.ts
src/linter/LintManager.ts

Add more logging messages

---

src/linter/SlangLinter.ts

currently diagnostics from other files would incorrectly show up in the current one, leaving very confusing messages. this fixes that.

Slang: only push diagnostics in the current file

---

README.md

fix for  #66, #84, #130, #142, #151, and #432

Update README.md for ctags

---

.github/workflows/publish-marketplace.yml

Automate release process

---

CHANGELOG.md
README.md
package.json
src/extension.ts

Adds the ability to configure additional arguments for the language servers

Pass arguments to LSP (#446)
