syntaxes/verilog.tmLanguage
Added a rule to allow highlighting of user-defined constants like
~~~
`define MY_CONSTANT 1'b0;
...
my_reg <= `MY_CONSTANT;  // MY_CONSTANT is now highlighted here
~~~
My regex excludes verilog compiler directives from the match (which I got from: http://verilog.renerta.com/mobile/source/vrg00008.htm). 
I also selected the scope `variable.other.constant` per the Sublime documentation here: https://www.sublimetext.com/docs/3/scope_naming.html
At first I thought `entity.name.constant` would be best, but after testing, most of the color schemes I tried worked better with `variable.other.constant`.
=> User defined constants

src/linter/IcarusLinter.ts
Dear maintainers,
Because reading custom Icarus Verilog arguments only happens when the configuration file was changed, custom arguments become `undefined` rather than the value on configuration files.
Please consider my changes and accept it if appropriate.
Thank you.
=> fix iVerilog linter arguments not loaded at startup

src/linter/IcarusLinter.ts
Fixes https://github.com/mshr-h/vscode-verilog-hdl-support/issues/16 - Linter now properly invoked for paths with spaces
Added few comments in iverilog linter code
=> Fixes for path with space

CHANGELOG.md, package.json, src/extension.ts
Added a feature to show a notification with an option to open the changelog when the extension gets updated [#14](https://github.com/mshr-h/vscode-verilog-hdl-support/issues/14)
=> Show notification to view Changelog after update

README.md, package.json, src/extension.ts, src/linter/VerilatorLinter.ts
i've added ventilator support. Enjoy.
=> Adding verilator support

CHANGELOG.md, README.md, package.json, src/extension.ts, src/linter/BaseLinter.ts
Added a command "Rerun lint tool" to manually run the linter #29 
Updated the README and CHANGELOG accordingly
Fixed a bug in the update notification
@terriblefire Your request to run a particular linter for a file can be partially fulfilled by this command, although you have to run in manually.
=> Added a command to manually run the linter

package.json, src/commands/ModuleInstantiation.ts, src/ctags.ts, src/extension.ts
Migrated "Module Instantiation" from [mshr/vscode-systemverilog-support](https://github.com/mshr-h/vscode-systemverilog-support)
Uses Ctags to find the modules and their ports from the file
Triggered using a command "Instantiate module"
referring #25
=> Added module instantiation

package.json, src/commands/ModuleInstantiation.ts, src/extension.ts, src/linter/LintManager.ts
While merging `sv` to `master`, the **Rerun Lint tool** command was left out. So, adding it back now.
Also a bug fix in **Module Instantiation** command where the module name is left out while instantiating.
=> Rerun lint tool was left out

CHANGELOG.md, src/linter/LintManager.ts
Fixing a bug that caused linter to run on all files. Now only runs on verilog/systemverilog files.
=> Bug: linter runs on all files

CHANGELOG.md, src/linter/LintManager.ts
Fixed the bug properly, that caused linter to run on non-verilog/sv files. Should be fine now.
=> Linter will now run only verilog/sv files - finally

package.json, src/linter/ModelsimLinter.ts
Modelsim linter now can also be run in the working directory of the file and has an extra option for the default library instead of `work`.
=> added options to the modelsim linter

CHANGELOG.md, README.md, src/linter/VerilatorLinter.ts
Added support for verilator on windows.
Verilator binaries for Windows are available at MSYS2 packages.
https://packages.msys2.org/base/mingw-w64-verilator
=> Added support for verilator on windows

package.json, syntaxes/codeblock.json
Add markdown support for verilog and systemverilog syntax highlighting.
This allows you to highlight verilog/systemverilog code in markdown code blocks.
=> Enable verilog/systemverilog syntax highlighting in markdown code block

src/ctags.ts
In javascript and typescript, it's not safe to not bound `this` in callback. It will cause undefined error when function callbacked. Here is some references: [Typescript Types and .bind](https://stackoverflow.com/questions/54710927/typescript-types-and-bind)
=> fix onDidChangeActiveTextEditor/onSave  callback `this` is undefined error

CHANGELOG.md, README.md, package.json, src/linter/VerilatorLinter.ts
Thanks for maintaining this great extension.  This adds a config option which, when enabled, rewrites the Verilator command to work correctly under WSL.  Node is not my first (or second or third) programming language and I'm happy to look at this if you don't like the way it's done.
=> Add support for Verilator under WSL

src/linter/VerilatorLinter.ts
Behaviour: Verilator v3.916 under WSL reports nothing.
Cause: The developer tools show `Cannot read property '0' of null` which indicates a failure to check illegal regex expressions.
Behaviour: Verilator v3.922 under Windows reports nothing.
Cause: The regex fails to match strings like: `%Error: c:/some/path/here/:26: syntax error, unexpected reg, expecting IDENTIFIER`
due to the stray colon by the path `c:`.
It also fails to match: `%Warning-WIDTH: /path/to/something:89:18: Some message here` due to stray `-`.
As per the format specification [here](https://www.veripool.org/wiki/verilator/Manual-verilator#List-of-all-warnings), I added a case for that too.
=> Include null check for Verilator regex

CHANGELOG.md, src/linter/XvlogLinter.ts
To avoid crash when some spaces exist in file path.
=> add double quotation marks for xvlog linter script

.gitignore, CHANGELOG.md, snippets/systemverilog.json, snippets/verilog.json
This pull request reorganizes the snippets included with the extension, making them easier to find, and adding other ones I think would be useful. This closes #128.
Here is a list of changes made:
- Slight update to .gitignore to prevent additional `.vscode` files from appearing.
- Updating prefixes on existing snippets to make them easier to find. For example, the prefix `always_ff` will also recognize `ff` being typed. Prefixes modified can be viewed for Verilog \([1](https://github.com/mshr-h/vscode-verilog-hdl-support/commit/37a516544d382d57e6c8bf7420ba0405abec1466#diff-8816d829a24ac0dd5f607a5a450eda9eaaa837e1b2c4d96331da0c0f1236384c), [2](https://github.com/mshr-h/vscode-verilog-hdl-support/commit/d4bd89b94659d283afd502033052bed30e1fe007#diff-8816d829a24ac0dd5f607a5a450eda9eaaa837e1b2 …
=> Adding and updating snippets

CHANGELOG.md, src/ctags.ts
To fix issue "Hover and definition jumps stop working" [#132](https://github.com/mshr-h/vscode-verilog-hdl-support/issues/132)
After switching documents in the tab bar, the Ctags symbol was cleared but not generated.
I added ctags.index() when switching documents.
=> Add Ctags indexing when switching documents

package.json, syntaxes/codeblock.json
* Remove unnecessary markdown activation event. (This is my mistake in #101)
* Update markdown codeblock syntax to match the latest [VSCode markdown syntax](https://github.com/microsoft/vscode-markdown-basics/blob/main/syntaxes/markdown.tmLanguage.json).
* ~~Add support for bsv, ucf, sdc, and xdc syntax to markdown codeblocks.~~
=> Update syntax for markdown codeblocks

package.json, src/ctags.ts, src/extension.ts, src/linter/LintManager.ts, src/linter/VerilatorLinter.ts, src/linter/XvlogLinter.ts, src/providers/DefinitionProvider.ts, src/providers/HoverProvider.ts
Hi.
This PR will fix following.
* `package.json`
- Fix description of `xvlog arguments` setting.
* `XvlogLinter.ts`
- Fix `xvlog arguments` setting requiring additional whitespace.
- Fix error message not being detected correctly if it contains brackets `[]`.
- Add support for warning messages.
* `VerilatorLinter.ts`
- Fix file paths being treated as regular expressions.
* `LintManager.ts`
- Add linting for open documents on launch.
* `extension.ts`
- Fix `Verilog: Rerun lint tool` command not working.
* `ctags.ts`, `DefinitionProvider.ts`, `HoverProvider.ts`
- Fix errors reported in the Developer Tools that the variable is undefined.
=> Fix linters and some errors

src/ctags.ts, src/linter/BaseLinter.ts, src/linter/IcarusLinter.ts, src/linter/LintManager.ts, src/linter/ModelsimLinter.ts, src/linter/VerilatorLinter.ts, src/linter/XvlogLinter.ts, src/providers/CompletionItemProvider.ts, src/providers/DefinitionProvider.ts, src/providers/DocumentSymbolProvider.ts, src/providers/HoverProvider.ts
Hi.
Thanks for merging #146!
This is additional fix that I mentioned in #146.
This PR contains two fixes:
* Fix ctags symbols not being updated in some cases.
For example, Hover does not work right after saving a document.
This fix adds the `getSymbols` function to the `CtagsManager` class to provide the correct symbols to all providers.
I have removed the `onDidChangeActiveTextEditor` event in `CtagsManager` as it is no longer needed.
* Share `DiagnosticCollection` between linters.
After executing the `Verilog: Rerun lint tool` command, error/warning messages will remain on the screen and cannot be erased.
This fix improves it by moving the `DiagnosticCollection` to the `LintManager`.
=> Fix ctags and linters

src/linter/VerilatorLinter.ts
If your workspace directory has a space in it, linting with verilator fails because the path is not properly escaped/quoted.
A temporary workaround is moving your workspace to a directory with no spaces in the path, but fixes it at the extension level.
Thanks for making such a useful extension!
=> fix: escape workspace directory

package.json
Include .svh extension for System Verilog.  This extension is often used for SystemVerilog header files.
=> Add .svh files for SystemVerilog parsing

package.json, src/ctags.ts
Added the ability to disable CTAG
To turn off, it is enough to write `none`, by analogy with Language Server.
I consider this function necessary, because not all users have CTAG. This also allows the extension not to create potentially disastrous requests.
=> Added the ability to disable Ctag

CHANGELOG.md, package.json
The default value of verilog.languageServer.enabled is changed from string "false" to boolean false.
This will solve the issue #332.
I found this setting is used only in the configLanguage Server function (in `src/extension.ts`).
So I believe any further change is required.
=> Set the default value of verilog.languageServer.enabled to false (Resolves #332)

CHANGELOG.md, README.md, package.json, src/extension.ts, src/providers/FormatPrivider.ts
=> Add Verilog-HDL formatting with iStyle Verilog Formatter 

CHANGELOG.md, README.md, package-lock.json, package.json, src/extension.ts, src/providers/FormatPrivider.ts
=> Add Verilog-HDL/SystemVerilog formatting with verible-verilog-format

CHANGELOG.md, README.md, package.json, src/extension.ts
Addresses #403
Tested with verible v0.0-2996-g781744e1 on ubuntu 22.04
=> Add experimental support for verible-verilog-ls (#403)

CHANGELOG.md, src/linter/SlangLinter.ts, src/linter/VerilatorLinter.ts
=> fix #418  slang and verilator  cant run under WSL

src/linter/SlangLinter.ts, src/linter/VerilatorLinter.ts, src/linter/XvlogLinter.ts
Similar issue to #139 for slang, verilator and xvlog.
Note, I only tested with slang and verilator
=> Add quotation marks around paths for Slang, Verilator and Xvlog

src/linter/VerilatorLinter.ts
Removes the space between the `-I` and the quoted include path, which breaks Verilator.
Resolves #421.
=> Fix Verilator linting include paths

src/linter/SlangLinter.ts
Fixes #426. Changed the regex so instead of searching for the longest string without "[" or "]", it will search for the smallest string which ends with the warning indicator (e.g. [-Wrange-oob]) or the end of the string (in the case of an error)
=> Fix slang warning message with square brackets

CHANGELOG.md, src/commands/ModuleInstantiation.ts, src/ctags.ts
NOTE: This pull request is not tested, because I don't have environment to test VS code extension.
---
By adding `--fields-SystemVerilog=+{parameter}` option uctag, it emits the 6th field, `parameter:`.
When `parameter:` is emitted, this fix override type as `parameter`.
In the following example `parameter:` are added on `P1` and `P2`.  This fix uses them.
```sh
$ cat with_parameter_port_list.sv 
module with_parameter_port_list #(
P1,
localparam L2 = P1+1,
parameter P2)
( /*port list...*/ );
parameter  L3 = "synonym for the localparam";
localparam L4 = "localparam";
// ...
endmodule
$ ctags -o - --fields=+K --sort=no --excmd=n with_parameter_port_list.sv 
with_parameter_port_list        with_parameter_port_list.sv     1;"     module
P1      with_parameter_port_list.sv     2;"     constant …
```
=> use uctag parameter field option for module instantiation (#102)

CHANGELOG.md, src/linter/SlangLinter.ts
fix it
https://github.com/mshr-h/vscode-verilog-hdl-support/issues/460
=> " slang: run at file location " seems not work correctly #460

src/providers/FormatPrivider.ts
This allows for --flagfile to be used, allowing for a single source of truth for formatter flags
=> [Formatter] execute from workspace folder

CHANGELOG.md, src/ctags.ts
Fixes the error reported here when the ctags path is set to none: https://github.com/mshr-h/vscode-verilog-hdl-support/issues/417
=> fix ctags indexing error if ctags path is set to none #417

src/commands/ModuleInstantiation.ts, src/ctags.ts, src/extension.ts, src/providers/CompletionItemProvider.ts, src/providers/DefinitionProvider.ts, src/providers/DocumentSymbolProvider.ts, src/providers/HoverProvider.ts
- Looks for symbol.sv in the repo when searching on hover and definition
- Package refs, modports follow their parent and search for that module/package/interface
- switched a bunch of stuff to async/await
- cleaned up logs
TODO (future work):
- This might leave indexed files in longer than they should be
- We should only be searching on module defs, not all symbols. It looks like we only find the kind of symbol defs, not any rhs
- have the async tasks race and cancel the lagging one
=> Support module definitions by looking for file name

README.md
From https://github.com/gediminasz/ctags-companion/releases/tag/v2023.8.0
- Switched to using the default tags file location rather than .vscode/.tags
- Replaced in-memory symbol index with more efficient readtags.
=> fix README.md for ctags-companion v2023.8.0 or later (#483)

CHANGELOG.md, src/ctags.ts
Added logging of stderr and exception handling for ctags exec call
Cosmetic fixes to the changelog
=> Better logging for ctags exection

CHANGELOG.md, src/commands/ModuleInstantiation.ts
=> Perfered_instantiation_indent

CHANGELOG.md, syntaxes/verilog.tmLanguage.json
Fix #476
Fix the issue of keywords being tokenized as entity.name.tag.module.reference.verilog instead of keyword.other.verilog to fix [#476](https://github.com/mshr-h/vscode-verilog-hdl-support/issues/476). This is done by adding a negative lookahead to the pattern of entity.name.tag.module.reference.verilog.
=> Iverilog_linting_bug

CHANGELOG.md, src/extension.ts
Fix #449 
Fix #487 
Modified the option of `veribleVerilogLs` to include a `messageStrategy` that handles and modifies the language server capabilities by removing unnecessary diagnostic and formatting providers. 
#449 and #487 occurred as the same features are provided twice by *HDL support* and *verible LS*. All things work fine now.
Please notice that this patch does not disable any features of *Verible LS*. Instead, they are just suppressed and letting VSCode  not able to realize that the language server provide these features. VSCode therefore has to turn to our extension for formatter and diagnostics.
=> Fix glitches caused by Verible LS

language_examples/systemverilog/implication.sv, syntaxes/systemverilog.tmLanguage.json, syntaxes/systemverilog.tmLanguage.yaml
=> Fix implication operator highlight

CHANGELOG.md, README.md, configs/verilogams.configuration.json, package.json, snippets/verilogams.json, syntaxes/verilogams.tmLanguage.json
- New files for VAMS Highlighting
- Updated package.json
- Updated CHANGELOG
- Updated README
=> Added Verilog-AMS Syntax Highlighter
